
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a random text passage for the Speed Typer game.
 *
 * - generateTypingText - A function to generate the text.
 * - GenerateTypingTextInput - The input type for the generateTypingText function.
 * - GenerateTypingTextOutput - The return type for the generateTypingText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTypingTextInputSchema = z.object({
  topic: z.string().describe('The topic for the text passage. e.g., "space exploration", "ancient history"'),
});
export type GenerateTypingTextInput = z.infer<typeof GenerateTypingTextInputSchema>;

const GenerateTypingTextOutputSchema = z.object({
  text: z.string().describe('A medium-length paragraph (about 40-60 words) on the given topic. The text should be engaging and suitable for a typing test.'),
});
export type GenerateTypingTextOutput = z.infer<typeof GenerateTypingTextOutputSchema>;

export async function generateTypingText(input: GenerateTypingTextInput): Promise<GenerateTypingTextOutput> {
  return generateTypingTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTypingTextPrompt',
  input: {schema: GenerateTypingTextInputSchema},
  output: {schema: GenerateTypingTextOutputSchema},
  prompt: `You are an assistant that creates content for a speed typing game. 
  
  Generate a single, interesting paragraph of about 50 words based on the following topic: {{{topic}}}.
  
  The paragraph should not contain complex punctuation, special characters, or line breaks. It should be a single block of text.
  `,
});

const generateTypingTextFlow = ai.defineFlow(
  {
    name: 'generateTypingTextFlow',
    inputSchema: GenerateTypingTextInputSchema,
    outputSchema: GenerateTypingTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
