
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a background image for a game based on a text prompt.
 *
 * - generateGameBackground - A function to generate the image.
 * - GenerateGameBackgroundInput - The input type for the generateGameBackground function.
 * - GenerateGameBackgroundOutput - The return type for the generateGameBackground function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateGameBackgroundInputSchema = z.object({
  prompt: z.string().describe('A text prompt describing the desired background image. e.g., "A mystical forest at dawn"'),
});
export type GenerateGameBackgroundInput = z.infer<typeof GenerateGameBackgroundInputSchema>;

const GenerateGameBackgroundOutputSchema = z.object({
  imageUrl: z.string().describe("The data URI of the generated image. Expected format: 'data:image/png;base64,<encoded_data>'."),
});
export type GenerateGameBackgroundOutput = z.infer<typeof GenerateGameBackgroundOutputSchema>;

export async function generateGameBackground(input: GenerateGameBackgroundInput): Promise<GenerateGameBackgroundOutput> {
  return generateGameBackgroundFlow(input);
}

const generateGameBackgroundFlow = ai.defineFlow(
  {
    name: 'generateGameBackgroundFlow',
    inputSchema: GenerateGameBackgroundInputSchema,
    outputSchema: GenerateGameBackgroundOutputSchema,
  },
  async ({prompt}) => {
    const {media} = await ai.generate({
      model: 'googleai/gemini-2.0-flash-preview-image-generation',
      prompt: `Generate a visually stunning, atmospheric, and slightly abstract background image suitable for a web game. The image should be artistic and not too literal. Theme: ${prompt}`,
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    if (!media?.url) {
      throw new Error('Image generation failed to produce an output.');
    }
    
    return { imageUrl: media.url };
  }
);
