
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides personalized feedback on a player's game performance.
 *
 * - getGameFeedback - A function to generate game feedback.
 * - GetGameFeedbackInput - The input type for the getGameFeedback function.
 * - GetGameFeedbackOutput - The return type for the getGameFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetGameFeedbackInputSchema = z.object({
  gameName: z.string().describe('The name of the game.'),
  score: z.number().describe('The player\'s final score.'),
});
export type GetGameFeedbackInput = z.infer<typeof GetGameFeedbackInputSchema>;

const GetGameFeedbackOutputSchema = z.object({
  feedback: z.string().describe('A short, witty, and personalized comment about the player\'s performance.'),
});
export type GetGameFeedbackOutput = z.infer<typeof GetGameFeedbackOutputSchema>;

export async function getGameFeedback(input: GetGameFeedbackInput): Promise<GetGameFeedbackOutput> {
  return getGameFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getGameFeedbackPrompt',
  input: {schema: GetGameFeedbackInputSchema},
  output: {schema: GetGameFeedbackOutputSchema},
  prompt: `You are a fun and witty game commentator.
  
  Based on the player's score for the game, provide a short (one-sentence) and encouraging comment.
  The comment should be personalized and feel like it's coming from a cool, supportive friend.
  Don't just state the score, comment on the performance it represents.
  
  Game: {{{gameName}}}
  Score: {{{score}}}
  
  Example for low score: "Nice try! Every pro starts somewhere, and you're on your way!"
  Example for medium score: "Not bad at all! You've got some serious skills."
  Example for high score: "Whoa, amazing score! Are you a wizard?"
  `,
});

const getGameFeedbackFlow = ai.defineFlow(
  {
    name: 'getGameFeedbackFlow',
    inputSchema: GetGameFeedbackInputSchema,
    outputSchema: GetGameFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
